### ISSUE TITLE
module 1 tests fail

### ISSUE THREAD

**Issue by YmerejRedienhcs** [mjuniper/ambitious-arcgis-app-2018#20]
pretty sure I did follow the steps in module 1, but it looks like a lot of tests failed.  Not sure how to show the results, but the attached file is a zipped movie of me running the tests

[ambitious_tests_fail.zip](https://github.com/mjuniper/ambitious-arcgis-app-2018/files/1777004/ambitious_tests_fail.zip)

**Comment by YmerejRedienhcs** [comment]
I re-did everything, and the tests pass now.

I think it was probably because I previously had ember-cli version 2.18.  Or maybe it was because I was using node 8.9?  

When I re-did everything, I also did the install of ember-cli, and it replaced the existing ember-cli version 2.x with version 3.0.0

**Comment by tomwayson** [comment]
Good to know. I assume this won't be an issue for most people since I assume very few people will come w/ 2.x installed, but we should check at the start of the course.

**Comment by MarkhamShofner** [comment]
@tomwayson 
![voyageambitiousarcgisapp tests 18_270](https://user-images.githubusercontent.com/14302394/36948070-fa3ce096-1f89-11e8-9e89-10d7673cede3.jpg) I'm also observing failing tests here. Going to poke at it a bit, but I'm assuming it's because we are on different versions of node.
