### ISSUE TITLE
suggestion: say "generate" the first time instead of "g"

### ISSUE THREAD

**Issue by YmerejRedienhcs** [mjuniper/ambitious-arcgis-app-2018#21]
the first time you have "ember serve" and then later you say "ember s".  That's cool, it helps people know.  Maybe you're going to say "g" is for generate.  I don't know.  But you might want to follow the same pattern, and the first time, instead of saying "ember g", do "ember generate".

**Comment by mjuniper** [comment]
I thought we were doing that. Will do, thanks.

**Comment by mjuniper** [comment]
Oh, actually we do.

https://github.com/mjuniper/ambitious-arcgis-app-2018/blob/master/workshop/1-building-an-app.md#add-items-route
